site_name: TumblMark
theme:
  name: material
  custom_dir: overrides
  font: false
  icon:
    admonition:
      quote: fontawesome/solid/repeat
    logo: material/notebook-heart
  palette:
    - primary: indigo
      accent: indigo
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - primary: indigo
      accent: indigo
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
#*****************************************************************
# Delete # from the below lines to enable a custom avatar.
# Be sure to leave all leading spaces intact!
#*****************************************************************
#extra:
#  avatar:
#    file: 'filename.jpg'
#    alt: 'Alt text for your avatar'
extra_css:
  - style.css
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - sane_lists
  - smarty
plugins:
  - blog:
      blog_dir: .
      post_url_format: 'post/{file}'
  - glightbox
  - search
  - tags